services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./time_reading:/time_reading

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
      
  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./time_reading:/time_reading
    links:
      - redis
      - celery-beat
    depends_on:
      - redis
      - celery-beat

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./time_reading:/time_reading
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

  celery-beat:
    build:
      context: .
    hostname: celery-beat
    entrypoint: celery
    command: -A celery_app.app worker --beat --scheduler django --loglevel=info
    links:
      - redis
    depends_on:
      - redis