# Generated by Django 4.2.6 on 2023-10-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_reading_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionreading',
            name='end_reading',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionreading',
            name='start_reading',
            field=models.TimeField(),
        ),
    ]
