# Generated by Django 4.2.6 on 2023-10-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_reading_system', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='seven_day_time_reading',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thirty_day_time_reading',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
