# Generated by Django 4.2.6 on 2023-10-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_reading_system', '0004_alter_userprofile_seven_day_time_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreading',
            name='date_end_reading',
            field=models.DateField(blank=True, null=True),
        ),
    ]
