# Generated by Django 3.2.22 on 2023-10-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_reading_system', '0005_sessionreading_date_end_reading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionreading',
            options={'ordering': ['date_end_reading']},
        ),
    ]
